#!/bin/sh

CUR_DIR=`dirname $0`
CUR_DIR=`pwd $CUR_DIR`
cd $CUR_DIR

ORIG_NAME="pyOpenSSL-0.11/"
NAME="python26-OpenSSL"
RELEASE=1
PACKAGER="Nick Bailey - nick@riptano.com"
DOC_FILES="README, PKG-INFO, ChangeLog, COPYING, INSTALL"
REQUIRES=""
BUILD_REQUIRES="latex2html, lynx, openssl-devel"

# copy to a directory for building
cp -r $ORIG_NAME $NAME/
#apply any patches
for patch_file in patches/*
do
    patch -p1 -d $NAME < $patch_file
done

# build rpms
cd $NAME
python2.6 setup.py bdist_rpm \
        --python="python2.6" \
        --dist-dir="$CUR_DIR" \
        --release="$RELEASE" \
        --packager="$PACKAGER" \
        --doc-files="$DOC_FILES" \
        --build-requires="$BUILD_REQUIRES"
cd ..

rm -r "$CUR_DIR/$NAME"

